INSERT INTO menu_items(name, description, price, picture_url, prep_time)
VALUES('The Original Combo', 'Delicious fresh ground beef patty with toasted non-sesame seed buns, lettuce , tomato and cheddar cheese paired with French fries and soda.', 15,'https://dw1ixebl10gex.cloudfront.net/wp-content/uploads/2015/08/04112806/crop-recipe-final-110412_HH_0390_REV1_SUP_HH_AU11_HH_JA21_79.png', 20),
('The American Combo', 'Delicious smashed beef patty topped with caramelized onion, cheddar, pickles, ketchup and mustard paired with French fries and soda.', 20, 'https://img.cdn4dd.com/p/fit=cover,width=150,height=150,format=jpeg,quality=50/media/photos/46ac20ec-9c85-439a-899f-f93c14530f6e-retina-large-jpeg', 25),
('The Shroom Combo', 'Delicious fresh ground beef patty with sauted mushrooms and swiss cheese paired with French fries and soda.',16, 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photos/18f522d1-fee0-4063-9319-64c00b072f85-retina-large-jpeg', 20),
('The Ring Combo', 'Grilled beef patty with onion rings, cheddar cheese, lettuce and tomato. Paired with French fries and soda.',18, 'https://www.vindulge.com/wp-content/uploads/2021/03/Western-Burgers-featured-image.jpg', 25),
('The BBQ Combo' , 'Braised beef in zesty BBQ sauce and topped with sauteed onions and cheddar cheese. Paired with French fries and soda.',20,'https://www.epicurus.com/food/recipes/wp-content/uploads/2011/09/bbq-cheeseburger.jpg', 30),
('The California Classic Double Combo', 'Two Grilled beef patties with sauteed onions, tomato, lettce and secret sauce. Paired with French fries and soda.',24, 'https://img.cdn4dd.com/p/fit=cover,width=150,height=150,format=jpeg,quality=50/media/photos/6d02866e-5a49-44ca-9c07-f029417c6648-retina-large.jpg', 45),
('The California Classic Single Combo', 'Two Grilled beef patties with sauteed onions, tomato, lettce and secret sauce. Paired with French fries and soda.',20, 'https://img.cdn4dd.com/p/fit=cover,width=150,height=150,format=jpeg,quality=50/media/photos/374e224e-a1bf-49da-90b5-4aadaefc57ee-retina-large.jpg', 30),
('The Crispy Chicken Combo', 'Deep fried and breaded chicken burger with brioche buns ,jalapenos and cheddar cheese paired with French fries and soda.',17, 'https://img.cdn4dd.com/p/fit=cover,width=150,height=150,format=jpeg,quality=50/media/photos/2efbd15a-a303-412a-8a10-b9441f84728d-retina-large.jpg', 20),
('The Melt Combo', 'Freshly breaded chicken breast with 3 layers of melted cheddar, lettuce and tomato. Paired with French fries and soda.',20, 'https://img.cdn4dd.com/p/fit=cover,width=150,height=150,format=jpeg,quality=50/media/photos/ea30b1e9-aa13-470d-9173-bbd8cdb53c55-retina-large-jpeg', 25),
('The Nashville Hot Chicken Combo', 'Fried chicken thigh dipped in Nashville style hot oil, creamy southern coleslaw, jalapenos and pickles.Paired with French fries and soda.', 23, 'https://img.cdn4dd.com/p/fit=cover,width=150,height=150,format=jpeg,quality=50/media/photos/38120fb8-b7f5-400f-9b23-fd1d785e4a10-retina-large-jpeg', 35),
('The Fish Combo', 'Fish patty with toasted non-sesame seed buns, cheddar cheese and lettuce. Paired with French fries and soda.', 15, 'https://www.thedinnerbite.com/wp-content/uploads/2021/04/fish-burger-filet-recipe-img-12.jpg', 15),
('The Vegeta Combo', 'Delicious vegetarian roll with roasted peppers, mushroom, lettuce, onion, tomato and cheddar cheese. Paired with French fries and soda.', 16, 'https://assets.bonappetit.com/photos/57acae2d1b33404414975121/4:3/w_3235,h_2426,c_limit/ultimate-veggie-burger.jpg', 20),
('The Veggie Lover Combo', 'A full portobello mushroom cap marinated in balsamic vinegar and soya sauce and topped with onion, roasted peppers and swiss cheese. Paired with French fries and soda.', 20,'https://i2.wp.com/www.pepperdelight.com/wp-content/uploads/2017/05/pepper-delight-portobello-mushroom-burger-4.jpg?w=1333&ssl=1', 30);


