DROP TABLE IF EXISTS cart CASCADE;

CREATE TABLE cart (
  id SERIAL PRIMARY KEY NOT NULL,
  menu_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
  item_name INTEGER REFERENCES menu_items(name) ON DELETE CASCADE,
  picture INTEGER REFERENCES menu_items(picture) ON DELETE CASCADE,
  price INTEGER REFERENCES menu_items(price) ON DELETE CASCADE,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  qty INTEGER REFERENCES order_items(id) ON DELETE CASCADE,
);
